rm -rf ../../thirdparty/tensorflow/
git clone https://github.com/tensorflow/tensorflow.git -b v2.0.0-alpha0 ../../thirdparty/tensorflow/
rm -rf ../../thirdparty/tensorflow/tools/
rm -rf ../../thirdparty/tensorflow/.git/
rm -rf ../../thirdparty/tensorflow/.github/
rm -rf ../../thirdparty/tensorflow/tensorflow/cc/
rm -rf ../../thirdparty/tensorflow/tensorflow/c/
rm -rf ../../thirdparty/tensorflow/tensorflow/core/
rm -rf ../../thirdparty/tensorflow/tensorflow/go/
rm -rf ../../thirdparty/tensorflow/tensorflow/java/
rm -rf ../../thirdparty/tensorflow/tensorflow/js/
rm -rf ../../thirdparty/tensorflow/tensorflow/examples/
rm -rf ../../thirdparty/tensorflow/tensorflow/compiler/
rm -rf ../../thirdparty/tensorflow/tensorflow/python/
rm -rf ../../thirdparty/tensorflow/tensorflow/tools/
rm -rf ../../thirdparty/tensorflow/tensorflow/contrib/
rm -rf ../../thirdparty/tensorflow/tensorflow/stream_executor/
rm -rf ../../thirdparty/tensorflow/tensorflow/g3doc/
rm -rf ../../thirdparty/tensorflow/tensorflow/docs_src/
rm -rf ../../thirdparty/tensorflow/third_party/android
rm -rf ../../thirdparty/tensorflow/third_party/aws
rm -rf ../../thirdparty/tensorflow/third_party/boringssl
rm -rf ../../thirdparty/tensorflow/third_party/clang_toolchain
rm -rf ../../thirdparty/tensorflow/third_party/examples/eager/spinn
rm -rf ../../thirdparty/tensorflow/third_party/flatbuffers
rm -rf ../../thirdparty/tensorflow/third_party/git
rm -rf ../../thirdparty/tensorflow/third_party/gpus
rm -rf ../../thirdparty/tensorflow/third_party/grpc
rm -rf ../../thirdparty/tensorflow/third_party/hadoop 
rm -rf ../../thirdparty/tensorflow/third_party/highwayhash
rm -rf ../../thirdparty/tensorflow/third_party/hwloc
rm -rf ../../thirdparty/tensorflow/third_party/icu 
rm -rf ../../thirdparty/tensorflow/third_party/jpeg
rm -rf ../../thirdparty/tensorflow/third_party/kafka
rm -rf ../../thirdparty/tensorflow/third_party/keras_applications_archive 
rm -rf ../../thirdparty/tensorflow/third_party/kissfft 
rm -rf ../../thirdparty/tensorflow/third_party/llvm
rm -rf ../../thirdparty/tensorflow/third_party/mkl 
rm -rf ../../thirdparty/tensorflow/third_party/mkl_dnn 
rm -rf ../../thirdparty/tensorflow/third_party/mpi 
rm -rf ../../thirdparty/tensorflow/third_party/mpi_collectives 
rm -rf ../../thirdparty/tensorflow/third_party/nasm 
rm -rf ../../thirdparty/tensorflow/third_party/nccl 
rm -rf ../../thirdparty/tensorflow/third_party/ngraph 
rm -rf ../../thirdparty/tensorflow/third_party/ortools
rm -rf ../../thirdparty/tensorflow/third_party/pasta
rm -rf ../../thirdparty/tensorflow/third_party/protobuf 
rm -rf ../../thirdparty/tensorflow/third_party/py
rm -rf ../../thirdparty/tensorflow/third_party/python_runtime
rm -rf ../../thirdparty/tensorflow/third_party/sycl
rm -rf ../../thirdparty/tensorflow/third_party/systemlibs 
rm -rf ../../thirdparty/tensorflow/third_party/tensorrt 
rm -rf ../../thirdparty/tensorflow/third_party/toolchains
../../thirdparty/tensorflow/tensorflow/lite/tools/make/download_dependencies.sh