#!/usr/bin/env python

Import('env')
Import('env_modules')

env_tensorflow = env_modules.Clone()
source = [
Glob('#thirdparty/tensorflow/tensorflow/lite/*.c'),
Glob('#thirdparty/tensorflow/tensorflow/lite/c/*.c'),
'#thirdparty/tensorflow/tensorflow/lite/core/subgraph.cc',
'#thirdparty/tensorflow/tensorflow/lite/core/api/error_reporter.cc',
'#thirdparty/tensorflow/tensorflow/lite/core/api/op_resolver.cc',
'#thirdparty/tensorflow/tensorflow/lite/core/api/flatbuffer_conversions.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/activations.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/add.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/basic_rnn.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/batch_to_space_nd.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/bidirectional_sequence_lstm.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/bidirectional_sequence_rnn.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/concatenation.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/conv.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/depthwise_conv.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/div.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/embedding_lookup.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/embedding_lookup_sparse.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/elementwise.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/eigen_support.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/exp.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/fake_quant.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/fully_connected.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/floor_mod.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/gather.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/gemm_support.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/hashtable_lookup.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/internal/kernel_utils.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/internal/quantization_util.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/internal/reference/portable_tensor_utils.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/internal/tensor_utils.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/internal/mfcc.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/internal/mfcc_dct.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/kernel_util.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/l2norm.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/local_response_norm.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/lsh_projection.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/lstm.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/lstm_eval.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/logical.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/mul.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/maximum_minimum.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/mirror_pad.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/pow.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/pad.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/range.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/pooling.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/register.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/resize_nearest_neighbor.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/reshape.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/resize_bilinear.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/skip_gram.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/squared_difference.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/space_to_batch_nd.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/space_to_depth.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/split.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/squeeze.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/strided_slice.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/sub.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/svdf.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/tile.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/topk_v2.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/transpose.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/unidirectional_sequence_lstm.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/unidirectional_sequence_rnn.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/bidirectional_sequence_lstm.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/bidirectional_sequence_rnn.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/zeros_like.cc',
'#thirdparty/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src/farmhash.cc',
'#thirdparty/tensorflow/tensorflow/lite/tools/make/downloads/fft2d/fftsg.c',
'#thirdparty/tensorflow/tensorflow/lite/allocation.cc',
'#thirdparty/tensorflow/tensorflow/lite/arena_planner.cc',
'#thirdparty/tensorflow/tensorflow/lite/graph_info.cc',
'#thirdparty/tensorflow/tensorflow/lite/interpreter.cc',
'#thirdparty/tensorflow/tensorflow/lite/model.cc',
'#thirdparty/tensorflow/tensorflow/lite/util.cc',
'#thirdparty/tensorflow/tensorflow/lite/mutable_op_resolver.cc',
'#thirdparty/tensorflow/tensorflow/lite/optional_debug_tools.cc',
'#thirdparty/tensorflow/tensorflow/lite/simple_memory_arena.cc',
'#thirdparty/tensorflow/tensorflow/lite/stderr_reporter.cc',
'#thirdparty/tensorflow/tensorflow/lite/nnapi_delegate_disabled.cc',
'#thirdparty/tensorflow/tensorflow/lite/mmap_allocation_disabled.cc',
'#thirdparty/tensorflow/tensorflow/lite/string_util.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/mfcc.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/fill.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/reduce.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/floor_div.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/audio_spectrogram.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/detection_postprocess.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/split_v.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/cast.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/dequantize.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/arg_min_max.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/floor.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/neg.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/comparisons.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/select.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/slice.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/expand_dims.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/transpose_conv.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/sparse_to_dense.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/unpack.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/pack.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/one_hot.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/shape.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/internal/spectrogram.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/internal/mfcc_mel_filterbank.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/where.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/unique.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/if.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/ceil.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/rank.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/reverse.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/gather_nd.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/add_n.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/while.cc',
'#thirdparty/tensorflow/tensorflow/lite/kernels/reverse_sequence.cc',
'#thirdparty/tensorflow/tensorflow/lite/minimal_logging_default.cc',
'#thirdparty/tensorflow/tensorflow/lite/minimal_logging.cc',
]

if (env["platform"] != "windows"):
    source.append(['#thirdparty/tensorflow/tensorflow/lite/nnapi_delegate.cc'])
    source.append(['#thirdparty/tensorflow/tensorflow/lite/mmap_allocation.cc'])

env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include'])
#env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow/tensorflow/lite'])
env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow/tensorflow/core'])
env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow/tensorflow/lite/tools/make/downloads/googletest/googlemock/include'])
env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow/tensorflow/lite/tools/make/downloads/googletest/googletest/include'])
env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow/tensorflow/lite/tools/make/downloads/absl'])
env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow/tensorflow/lite/tools/make/downloads/eigen'])
env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src'])
env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp'])
env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow/tensorflow/lite/tools/make/downloads/fft2d'])
env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow/tensorflow/lite/schema'])
env_tensorflow.Prepend(CPPPATH=['#thirdparty/tensorflow'])

if (not env.msvc):
    env_tensorflow.Append(CXXFLAGS="-std=c++11")

#env_tensorflow.Append(CXXFLAGS=['-DTF_COMPILE_LIBRARY'])
env_tensorflow.Append(CXXFLAGS=['-DFARMHASH_CAN_USE_CXX11'])
env_tensorflow.Append(CXXFLAGS=['-DFARMHASH_OPTIONAL_BUILTIN_EXPECT'])
#env_tensorflow.Append(CXXFLAGS=['-DTFLITE_MCU'])

if (env.msvc):
    env_tensorflow.Append(CXXFLAGS=['-DEIGEN_AVOID_STL_ARRAY'])
    env_tensorflow.Append(CXXFLAGS=['-DCOMPILER_MSVC'])
    env_tensorflow.Append(CXXFLAGS=['-DTENSORFLOW_USE_EIGEN_THREADPOOL'])
    env_tensorflow.Append(CXXFLAGS=['-DEIGEN_HAS_C99_MATH'])

env_thirdparty = env_tensorflow.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(env.modules_sources, source)

# Godot's own source files
env_tensorflow.add_source_files(env.modules_sources, "*.cpp")
